# EKS cluster configuration for the Hospital Management application.
#cluster will be creaetd and deploy app through the clusetr 
# Provision with: eksctl create cluster -f eks/cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hospital-eks
  region: ap-southeast-2    # Sydney.
  version: "1.30"

iam:
  withOIDC: true            # needed for the EBS CSI driver IAM role

managedNodeGroups:
  - name: ng-workers
    instanceType: t3.medium
    desiredCapacity: 2          # HA: 2 worker nodes
    minSize: 2
    maxSize: 3
    volumeSize: 20
    privateNetworking: true     # nodes go into PRIVATE subnets (no public IP); reach them via the bastion in the public subnet

addons:
  - name: aws-ebs-csi-driver   # real persistent storage (Phase 8); auto-creates IAM role
    wellKnownPolicies:
      ebsCSIController: true
